// File generated by getx_clean_arch CLI.
// Replace with actual Firebase configuration from FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Check flavor
    const flavor = String.fromEnvironment('FLAVOR', defaultValue: 'dev');
    
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return flavor == 'prod' ? androidProd : androidDev;
      case TargetPlatform.iOS:
        return flavor == 'prod' ? iosProd : iosDev;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  // DEV - Android
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_API_KEY',
    appId: 'YOUR_DEV_APP_ID',
    messagingSenderId: 'YOUR_DEV_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_STORAGE_BUCKET',
  );

  // DEV - iOS
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'YOUR_DEV_API_KEY',
    appId: 'YOUR_DEV_APP_ID',
    messagingSenderId: 'YOUR_DEV_SENDER_ID',
    projectId: 'YOUR_DEV_PROJECT_ID',
    storageBucket: 'YOUR_DEV_STORAGE_BUCKET',
    iosBundleId: 'com.example.app.dev',
  );

  // PROD - Android
  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_STORAGE_BUCKET',
  );

  // PROD - iOS
  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'YOUR_PROD_API_KEY',
    appId: 'YOUR_PROD_APP_ID',
    messagingSenderId: 'YOUR_PROD_SENDER_ID',
    projectId: 'YOUR_PROD_PROJECT_ID',
    storageBucket: 'YOUR_PROD_STORAGE_BUCKET',
    iosBundleId: 'com.example.app',
  );
}
